name: Linux Workflow
on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps: 
          - name: echo a string
            run: echo "Hello World"
          - name: multilines commands
            run: |
              node -v
              npm -v  

    